### PR TITLE
Use python3 instead of python in your_git.sh

### PR DESCRIPTION
**Pull request by tapankavasthi**
- Why this change is needed?
When python3 isn't set as the default python interpreter, the script, `your_git.sh` would fail to execute as the demo code uses python3 specific syntax.

- What's the change?
Change is straightforward, `python` is changed to `python3`

### CODE REVIEW

**Comment by rohitpaulk** [comment]
@tapankavasthi could you send this to https://github.com/codecrafters-io/languages instead? That way, it'll automatically run tests with the docker image to make sure nothing breaks 🙂

**Comment by rohitpaulk** [comment]
Here's the file you'll need to edit: https://github.com/codecrafters-io/languages/blob/master/starter_templates/git/python/your_git.sh

**Comment by tapankavasthi** [comment]
Sure, I've raised this [PR](https://github.com/codecrafters-io/languages/pull/38). Waiting for tests to pass, post which it shall be ready for your review there.

**Comment by rohitpaulk** [comment]
Neat. Thanks!

**Pull request closed without merging**
